
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 08 18:25:09 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDES = 41;
  public static final int LBRACKET = 9;
  public static final int INCREMENT = 28;
  public static final int CHAR = 48;
  public static final int CONST = 8;
  public static final int NOTEQUAL = 35;
  public static final int GREATER = 36;
  public static final int LPAREN = 13;
  public static final int SEMI = 5;
  public static final int CONTINUE = 19;
  public static final int LESS = 38;
  public static final int MINUS = 33;
  public static final int DECREMENT = 29;
  public static final int RPAREN = 14;
  public static final int AND = 30;
  public static final int LESSEQUAL = 39;
  public static final int OR = 31;
  public static final int BOOL = 49;
  public static final int COMMA = 6;
  public static final int CLASS = 11;
  public static final int PLUS = 32;
  public static final int ASSIGN = 7;
  public static final int IF = 16;
  public static final int DOT = 24;
  public static final int EOF = 0;
  public static final int RETURN = 21;
  public static final int RBRACKET = 10;
  public static final int EQUAL = 34;
  public static final int NEW = 27;
  public static final int error = 1;
  public static final int MODULO = 42;
  public static final int NUMBER = 47;
  public static final int IDENT = 46;
  public static final int BREAK = 20;
  public static final int VOID = 15;
  public static final int GREATEREQUAL = 37;
  public static final int TIMES = 40;
  public static final int COLON = 44;
  public static final int FOREACH = 25;
  public static final int LBRACE = 3;
  public static final int ELSE = 17;
  public static final int ENUM = 43;
  public static final int READ = 22;
  public static final int WHILE = 18;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 12;
  public static final int PROG = 2;
  public static final int RIGHTARROW = 26;
  public static final int DO = 45;
  public static final int PRINT = 23;
}

